version: '3.8'
name: properview
services:
  database:
    image: postgres
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - properview_pgdata:/var/lib/postgresql/data

volumes:
  properview_pgdata:
